//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.ServiceInterface")]
    public interface ServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceInterface/GetDatafromDB", ReplyAction="http://tempuri.org/ServiceInterface/GetDatafromDBResponse")]
        System.Data.DataSet GetDatafromDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceInterface/GetDatafromDB", ReplyAction="http://tempuri.org/ServiceInterface/GetDatafromDBResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDatafromDBAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceInterfaceChannel : BusinessLayer.WCFService.ServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceInterfaceClient : System.ServiceModel.ClientBase<BusinessLayer.WCFService.ServiceInterface>, BusinessLayer.WCFService.ServiceInterface {
        
        public ServiceInterfaceClient() {
        }
        
        public ServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDatafromDB() {
            return base.Channel.GetDatafromDB();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDatafromDBAsync() {
            return base.Channel.GetDatafromDBAsync();
        }
    }
}
